### ISSUE TITLE
Urukul power

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#198]
@gkasprow 

* Regarding VFB1 and VFB2 of that LTM4619EV: don't you want to tap them from the same side of the choke in both cases?
* Are there more quiet, smaller, cheaper converters (2x2A instead of 2x4A) since we'll go for just the 4x AD9912/AD9910 and 4x 35 mA @ 7V  ERA-3+ amplifiers?

**Comment by gkasprow** [comment]
@jordens right, the feedback path should be identical.
I used this converter mainly because we use it already on Sayma RTM and it is low noise chip since all components are integrated in it. It also has high efficiency.
We could go for discrete version but they generate more EMI due to bigger physical size and have worse efficiency. We can go for 2.5A version - LTM4622 but is has lower efficiency.

**Comment by jordens** [comment]
OK. I'll leave it to you then.
