### ISSUE TITLE
Urukul: AD9910 synchronization

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#213]
@dhslichter @r-srinivas
Looks like the AD9910 has the same synchronization circuitry as the AD9914/AD9915. Could you review the way this is used and how it should be wired for Urukul?
RIght now, the plan (still only on the wiki, not the schematics) would be to have:

* REFCLK delay-matched fan-out to the DDS. In the case where the DDS each uses its own internal PLL to get from e.g. 100 MHz to 1 GHz this would be 100 MHz. This should work fine if the PLL does an integer ratio.
* SYNC_CLK from DDS0 to the FPGA for monitoring/debugging and potentially timing IO_UPDATE
* SYNC_OUT from DDS0 to the FPGA for monitoring/debugging
* a delay-matched fan-out from SYNC_OUT to DDS0-3:SYNC_IN where SYNC_OUT is either DDS0:SYNC_OUT or generated by the FPGA (solder jumper).

Is that sufficient as a first iteration to get SYNC_CLK of the four DDS on one board synchronized?

**Comment by dhslichter** [comment]
Yes, this should be sufficient.  Because the max DDS clock is only 1 GHz, meeting the timing should be substantially easier than with the AD9914.  We have successfully used the CDCLVC1112 for distributing the LVCMOS clocks; for Urukul you could use the 6-channel version, CDCLVC1106, to make 6 matched copies of DDS0:SYNC_OUT, to feed to the four DDS chips and to the FPGA diagnostic monitoring.  For the REFCLK fanout, I'd just use the same parts as from Sayma.  

For the DDS0:SYNC_CLK monitor, I assume you will convert to LVDS on the board for transmission to the FPGA; if not, keep in mind that the SYNC_CLK output is not able to source very much current.  

One thing that is very helpful to have, but not strictly necessary, is a loopback for IO_UPDATE to the FPGA.  That way you can use the FPGA to compare the timing of IO_UPDATE and SYNC_CLK at the plane of the DDS inputs, and perform the necessary phase shifting of IO_UPDATE (or potentially also an FPGA-generated SYNC_OUT, if desired) to ensure all setup times are met for IO_UPDATE.  More relevant for pulsed work than for noise-eating.

**Comment by jordens** [comment]
thanks!
