### ISSUE TITLE
Urkul output BALUN

### ISSUE THREAD

**Issue by jordens** [m-labs/sinara#272]
We should [probably](https://ww2.minicircuits.com/app/AN20-002.pdf) go for the standard center-tapped transformer instead of the trifilar TLT. The original design came over from Allaki which wants to go to higher frequencies. But for the usual DDS applications and frequencies the center-tapped trafo seems more suitable. It's also what's on all the eval boards.

Nominally TR1 [should be](https://github.com/m-labs/sinara/issues/199#issuecomment-304343253) a 1:sqrt(2) transformer. Does minicircuits have anything closer to that (e.g. 1:1.5)? Or is 1:2 already optimized for some reason I don't see? There is a 1:1 on the [AD9910 eval board](https://static5.arrow.com/pdfs/2009/9/10/19/9/32/656/adi_/auto/ad9910_schematics.pdf) and a 1:2 on the [AD9912 board](http://www.analog.com/media/en/evaluation-boards-kits/evaluation-board/AD9912_Schematic.pdf).

Also, the AD9912 DAC output is externally differentially terminated with 100 Ohm on the [eval board](http://www.analog.com/media/en/evaluation-boards-kits/evaluation-board/AD9912_Schematic.pdf) in front of the 1:2 transformer.

**Comment by gkasprow** [comment]
@jordens  Minicircuit specifies impedance ratio, not turn ratio. So 1:2 should be fine.

**Comment by jordens** [comment]
Oh. Thanks for clarifying.  But then is the eval board wrong? And what about the 100 ohm resistor on the ad9912 board?

**Comment by dhslichter** [comment]
IME one shouldn't take the balun ratios and populated resistances too literally, especially because the output impedances of the DDS chips can vary substantially over frequency.  When working with the AD9914, I found that doing the "expected" thing gave worse performance than the way it was set up on the eval board at higher frequencies, although better at lower frequencies.  

Usually there are design files with measured output impedances that exist, which one can combine with measured S parameters of baluns to do a simulation.  Looks like the AD9912 has an internal 100 ohm differential termination already (they claim on the datasheet), and the eval board has [optional resistor pads](http://www.analog.com/media/en/evaluation-boards-kits/evaluation-board/AD9912_Schematic.pdf).  Someone with a network analyzer should look at the return loss looking into the output of the DDS via the balun with and without those resistors populated and see what you get.

**Comment by gkasprow** [comment]
@dhslichter I can check with network anayzer at the devkit output. I assume that DDS needs to be powered on.

**Comment by dhslichter** [comment]
@gkasprow yes, power on the DDS, turn on the output to some reasonable value and check the return loss at the devkit output.  Then play with balun choice and/or termination resistors at DDS output until you find something that matches reasonably well in the band of interest.

**Comment by gkasprow** [comment]
@dhslichter I'm not sure if measurements taken with signal at the DDS output would be representative.
I can make measurements quickly but optimisation would have to wait.

**Comment by dhslichter** [comment]
You can set the amplitude to zero if you want.  If the amplitude is nonzero, you'll get some spike in your S11 at the signal frequency but just ignore that spike and look at the frequencies to the side.  I would at least check with zero amplitude vs nonzero amplitude to see if it makes a difference to the impedance match (it shouldn't, but there could be higher order considerations).

Agreed that right now we just want to see if the eval board solution is good enough, and if so, we won't worry about optimizing.

**Comment by jordens** [comment]
Also here @gkasprow let's focus on getting prototypes out. We can optimize the baluns later on the prototypes.

**Comment by gkasprow** [comment]
I changed it to ADT1-1WT+ used on 9910 devkit which is footprint compatible with ADT2-1T-1P used on 9912 devkit.

**Comment by jordens** [comment]
Could we also get updated BOMs?
