### ISSUE TITLE
Nanoga schematic review

### ISSUE THREAD

**Issue by gkasprow** [m-labs/sinara#385]
@hartytp We have to produce prototypes of Nanoga board to finish the project at the University this year.
Did you have a time to look at the schematics and PCB?

**Comment by hartytp** [comment]
@gkasprow I hand't realized that Nanonga had been done!

I'll have a look tomorrow.

In the mean time, please can you confirm that all relevant Allaki bug fixes have been applied to Nanonga?

**Comment by gkasprow** [comment]
Well it had been done long time ago but there were more important things...
@sbouhabib Please check what @hartytp wrote about Allaki [issues](https://github.com/m-labs/sinara/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+allaki)

**Comment by hartytp** [comment]
@gkasprow My biggest concern with producing this PCB now is the unresolved Sayma mechanical issues to do with SMPs etc. e.g. what if we decide that using this many SMPs for the AFE is too expensive/not mechanically good and we want to find a different solution for Sayma v2.

If at all possible, I'd prefer to hold off producing this PCB until we've decided what changes to make for Sayma V2. However, if that's not an option due to rules of your University we can go ahead.

**Comment by gkasprow** [comment]
We can integrate @jbqubit idea of a screw-based ejection mechanism. Could be easy to implement on Nanoga right now.
Other connector idea:
http://suddendocs.samtec.com/catalog_english/grf1-j.pdf
https://www.samtec.com/products/grf1-p
they are also quite [expensive](https://www.digikey.com/product-detail/en/GRF1-P-P-02-E-ST-TH1/SAM8075-ND/1112918?utm_campaign=buynow&WT.z_cid=ref_octopart_dkc_buynow&utm_medium=aggregator&curr=usd&site=us&utm_source=octopart)

**Comment by gkasprow** [comment]
@hartytp we can try to sign an annex to the agreement that prolongs this particular project.

**Comment by hartytp** [comment]
Something like the IP5/IJ5 might be a better choice. If we buy a single 10-way high-isolation connector we'll probably find that it's mechanically a lot better than having many SMPs, and may not be more expensive.

**Comment by gkasprow** [comment]
I looked at them but their stacking height is 10mm, we need max 9 mm.

**Comment by hartytp** [comment]
Okay, that makes sense. In any case, something like that could be a better solution than the SMPs.

The more I think about it, the more I wonder whether it would also be better to make mezzanines double width (2 per Sayma rather than the current 4) so that they each take 4 DAC/ADC channels. This change might make some of the mechanical issues a bit easier (it also reduces the number of RF connections since the LO is shared between more channels).
 
Anyway, this is a conversation best had later on when we consider the next version of Sayma.

**Comment by gkasprow** [comment]
@hartytp  I looked at IP5 and IJ6 connector once again and noticed that there is some undocumented feature - the IJ5 part has one vertical size while  IP5 has additional parameter in the symbol name and this number specifies stacking option.
So I downloaded 3D models and indeed, the stacking height varies.
Let's take 
IH5-06-05.0-L-D-1-TR
and   IP5-06-02.0-L-D-1-TR
With connector above combined I get 7.5mm
With connector IP5-06-03.0-L-D-1-TR I got exactly 9mm!!
So it seems this could be good solution.
There are either 2x4 or 2x6 connectors so in our case we would need to use 12 way one. We can use remaining pair for i.e. delivery of two copies of LO signal to make construction of the AFE board easier - we have free outputs in ADCLK chip anyway.

**Comment by hartytp** [comment]
@sbouhabib Out of curiosity, what are your thoughts on IQ mixer choice for this design? Our top priority is phase + amplitude stability versus temperature (although, phase noise and linearity are also important). That mixer seems nice, but I haven't looked carefully for better choices. Did you look at other options? Are you happy there there isn't a significantly better alternative available?

**Comment by hartytp** [comment]
Starting my review:


- [ ] Add version number (v1.0) to schematic
- [ ] On ADC channel page, "Variant" not "Wariant" (this is wrong in Allaki as well)
- [ ] Let's remove RF_OUT1 SMA, so we just have a single SMA, labelled "OUT" on the schematic + silk.
- [ ] Let's remove the ADC_IN_1 SMA, and all components associated with it, including the InAmp. I don't see any need for this InAmp. We then have just a single input SMA labelled "IN" on the schematic + silk.
- [ ] Why use the ADCLK944 instead of the two-output ADCLK925 (which has slightly better performance IIRC)? Is the 944 cheaper or something?
- [ ] Why generate the 3V3 from the 5V0, rather than directly from the 6V0?
- [ ] Why do the resistors on the ADC channel page not match the values given in the table? e.g. R1 should be 681R according to the table?
- [ ] Text is upside down for C4, R40, R42, C63 (also wrong on Allaki)
- [ ] Can you add an annotation on the demodulator page giving the max input power, please?
- Filters:
  - [ ] I think it's worth having a filter on the DAC outputs before the mixer to reject images. I'm assuming we'll use interpolation with a DAC clcok frequency >= 2GHz. Max RF output frequency is 400MHz so (@jordens correct me if I'm wrong about this) the bulk of what we're trying to filter out will be at frequencies above 1.6GHz. Pick whichever filter you want that will pass 400MHz but block above about 1.5GHz. I didn't find any nice differential filters, so we could either build our own out of discrete passives or do something like use 2 x XLF-641M+ for each DAC (please double check that there isn't a more suitable part before using!). I don't mind whether you use the discrete filter or the MCL; do whichever is easier/cheaper/better (just make sure you annotate the schematic with the passband etc).
  - [ ] Let's put the same filter on the demodulator output (easier than using the passive filter IMO) to remove RF that will be rectified by the following OpAmp.
  - [ ] Is there any point having a filter after the mixer? If not, please remove it (both the passive and the MCL version). The current filter won't work too well as it only goes to 3GHz, and our target frequencies are up to 3.2GHz. My feeling is that if the IQ mixer is set up properly, the carrier and LO feed through should generally be low enough to not need filtering. In any case, given the range of values for the LO and RF that one can imagine using this board with, I can't see a good default value for this filter, so it's probably best for users to add an external filter if they really need it.
  - [ ] There should be a basic high-pass filter between the modulator and the amplifier to prevent any baseband leakage from reaching the amplifier. Please add an annotation for this filter specifying corner frequency etc.
- [ ] Please add an annotation with the power out of the IQ mixer when the DAC is running at max amplitude. Do we need an attenuator between the mixer and the amplifier to avoid saturating the amplifier or other components when the DAC is running at max amplitude? Should we have an attenuator like this on Allaki as well?
- [ ] What are R18 and R19 for? Either they should be DNF or IC4 + U1 should be DNF AFAICT.
- [ ] Let's make sure that we're using the cheapest substrate that will provide acceptable performance up to at least 4GHz.
- [ ] +-5V regulators must have diodes
- [ ] Is it worth putting inductors on the +-12V rails to remove high-frequency noise (these are generated by SMPSs on Sayma IIRC)? This is probably a good idea since there is no regulator on the supplies used for the InAmps. If we do this, we should also do this for Allaki.
- [ ] It would be nice to have a solder jumper to allow one to connect the analog input directly to the ADC, bypassing the InAmp, as is done on Allaki. If this is hard to do because of routing concerns then don't worry, it's not critical.
- [ ] Let's scrap the power detector and associated components . I really don't think this is very useful because:
  - The 24-bit ADC is so slow that it will take ages to read this out, making it annoying to use in most cases.
  - The dominant source of drift will generally be external power amplifiers.
- [ ] If the routing can be done easily, let's route the unused output of the RF switch (the one that currently connects to the power detector) to the demodulator via a solder jumper. In that way, one can use the demodulator as a fast power detector if wanted. If the routing for this is difficult, or likely to lead to cross-talk issues then don't bother.
- [ ] Should probably have a power budget on the schematic like the ones for the EEMs. This applies to Allaki as well.
- [ ] If we make this board a bit narrower, will that avoid some of the mechanical issues we've had with Allaki?
- [ ] Remove annotation "input considerations and Variants ...”
- [ ] Input/output SMA coupling caps should be 2*1nF on each SMA. (Why are there three caps on the input SMA?)
- [ ] Add part number to TR1 on the schematic
- [ ] Do we we need a bit of attenuation between the clock mux that supplies the and the (de)modulator? For lower LO values (below about 3GHz), the mux supplies 1.5Vpp differential signal = +8dBm. But, the (de)modulator wants a max LO input power of +6dBm. Let's aim for the max LO power (i.e. power for frequencies <2GHz) to be a little below +6dBm after the balun
- [ ] Demodulator output needs to be DC coupled, since we will generally user this with the RF at the same frequency as the LO. Note the common-mode offset on these signals.
- [ ] Demodulator load should be 450Ohm differential typically (ie not 50Ohm terminated). Currently, both demodulator outputs are terminated in 50R to GND AFAICT. These signals need to be properly matched into the differential ADC driver to ensure that the max signal amplitude corresponds to the max differential signal the ADC can accept. We should probably have three entries in the component value table: for InAmp; 1 for 50Ohm input direct to the ADC driver; and, one for the demodulator.
- [ ] IQ_DEMOD_I_P and IQ_DEMOD_Q_N inputs on ADC driver page should really just be IQ_DEMOD_P and IQ_DEMOD_N since this is used as both an I and a Q input.
-  [ ] Demodulator enable input is active low. This should be noted on the schematic (e.g. label this signal with a bar over the top). I'd like the demodulator to be enabled when this signal is not actively driven, so this pin should be pulled low, not high as in the current design. Similarly, please can we have the modulator disable input pulled low by default? That way we don't have to actively drive these pins to make the board work.
- [ ] Our LO frequency will typically be a bit below 3GHz. From figure 13 of the demodulator data sheet, the optimal Vadj is about 4.25V. From table 4, the optimal value for R77 is probably 1k (although 1k5 should be fine too). Please double check the best value for a 3GHz LO and add an annotation saying that R77 and R90 are chosen for best performance for LO at 3GHz.
- [ ] What are C45, R69, etc for? Can we scrap these? There are quite a few components on this PCB for matching, which I don't anticipate using, but which take up space. Would it be worth removing some of them?
- [ ] Modulator IQ inputs must be biased to +500mV by the DAC. If I understand correctly, the biasing resistors have been chosen so that with 20mA full-scale DAC current the common-mode voltage offset is 500mV and the swing is 1Vpp (+4dBm), while still providing a decent 100R differential termination to minimise reflections. Is that correct? This info should all be annotated on the schematic.
- [ ] In the current schematic, the jumper arrangement to connect the demodulator is not clear to me. Could you improve the annotation to make it clear how this works (maybe a little diagram like the other diagram for jumpers?). The default population option should have the demodulator connected.

**Comment by dhslichter** [comment]
See https://github.com/m-labs/sinara/issues/368#issuecomment-347983013, one can reduce the SMP mating/demating forces by using smooth bore SMP.  I am not saying this is the best alternative, but can be used.

**Comment by jordens** [comment]
Yes. You should reconstruct after the DAC. But you need to decide which mix mode/Nyquist image you want. In the first zone you have 450 MHz bandwidth and then the first images to be suppressed from 1.55 GHz up (1 GS/s data, 2x interpolation).

**Comment by hartytp** [comment]
> Yes. You should reconstruct after the DAC. But you need to decide which mix mode/Nyquist image you want. In the first zone you have 450 MHz bandwidth and then the first images to be suppressed from 1.55 GHz up (1 GS/s data, 2x interpolation).

Thanks for confirming!

My feeling is that this board is only going to be used in the first nyquist zone. I don't see so much use case for using the DAC in mixer mode in combination with an analogue mixer. In any case, so long as we chose a filter with a sensible package, users can change this later if needs be.

**Comment by dhslichter** [comment]
Definitely want a reconstruction filter before the mixer, and a good one.

**Comment by hartytp** [comment]
Having given this some more thought, I'd like to drop the Nanonga name and just call this the Sayma Upconverting AFE. If people make more upconverting AFEs in the future then we can call them "Upconverting AFE 2" etc. IMHO that's at least as unique and clear as giving them names like Nanonga etc.

Unless @jbqubit et al object, I'd advocate for renaming Allaki "Sayma Baseband AFE" in the next revision.
