### ISSUE TITLE
add an XO on Sayma RTM

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/sinara#71]
On MGTREFCLK0_216 for RTM<->AMC transceiver link debugging. 50MHz.

**Comment by gkasprow** [comment]
@sbourdeauducq 
what about using pair of ufl connectors to deliver 100MHz clock from one of ADCLK muxes?
I don't have any 50MHz differential oscillators.
Since it is for debugging only, you can install ufl to ufl jumpers and deliver 100MHz to any ufl you want
So I added pair of ufl for both AMC and RTM FPGA GTP clock inputs

**Comment by sbourdeauducq** [comment]
A quick Digikey search turned up a number of XOs with LVDS output. I suggest putting a footprint for one of those and keeping it a placeholder (DNP) for now.

**Comment by gkasprow** [comment]
I mean that I don't have in my libraries:)
I will create one.

>
>

**Comment by sbourdeauducq** [comment]
OK thanks.
